language: ruby
rvm:
 - 2.4.2
before_install:
  - gem update --system
  - gem install rake
  - gem install bundler
before_script: 
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
script: bundle exec rake spec
